### ISSUE TITLE
Error importing JSON: Duplicate entry found. Multiple values of '' found for .

### ISSUE THREAD

**Issue by andreassolberg** [TryGhost/wp-ghost-exporter#6] opened 2016-05-26 12:42 UTC
I get two of these strange errors when importing the JSON generated by the ghost exporter.

```
Duplicate entry found. Multiple values of '' found for .
Duplicate entry found. Multiple values of '' found for .
```

Here is the JSON export if it is helpful to debug:
- https://dl.dropboxusercontent.com/u/2381403/wp2ghost_export_1464266396.json

**Comment by ErisDS** [comment] 2016-05-27 18:38
Thank you SOOOOO much for including the export! That makes it much, much easier to track down the issue.

The '' and the . are supposed to have useful information between/before them to tell you what is wrong. Not sure why that's not happening, and going to cc @cobbspur here as I think he's had a similar issue.

I think the problem is most likely with the importer in [Ghost](https://github.com/TryGhost/Ghost) rather than the exporter here, but we'll confirm that first and then try to find a resolution.

Thanks again!

**Comment by DrXorile** [comment] 2016-11-23 01:10
Similar problem for me importing from tumblr. Has there been any resolution on this? I saw elsewhere that it could be related to block quotes? I tried to remove all the blockquotes, and the problem remained.

So I just tried to import the example document from [here](http://tumblr-to-ghost.herokuapp.com/), which is found [here](https://gist.github.com/jpadilla/7290464). The same error occurred.

I also tried to export the initial contents, then delete the blog and then import what I had exported. This also failed with "Transaction query already complete, run with DEBUG=knex:tx for more info".

**Comment by xDEADC0DE** [comment] 2017-04-09 22:19
I've had the same problem with my import. Actually I had the error show up _twice_.

**Comment by xDEADC0DE** [comment] 2017-04-09 22:20
One of them was due to 2 tags who had the same "slug". This may also be the case for 2 blog posts, I'm looking into it.

(edit) actually, solving the duplicate tag "slug" removed both error messages :)

**Comment by nuclearpengy** [comment] 2019-10-05 23:11
Since the export format has changed quite a bit, I think it's safe to close this issue.

**Closed as completed** 2019-10-07 16:38 UTC

**Comment by xDEADC0DE** [comment] 2019-10-07 17:36
If it's fixed it's fixed ;)
